#!/bin/bash
if [ "$freedom_context" == "" ]; then
    #load environement variable for freedom
  . /etc/freedom.conf
   wchoose -b
fi

#------------------------------
#post installation
#------------------------------
if [ "$1" = "I" ] ; then

  echo

fi

#------------------------------
#post update
#------------------------------
if [ "$1" = "U" ] ; then

  echo

fi

#------------------------------
#post uninstallation
#------------------------------
if [ "$1" = "D" ] ; then

  echo
  
fi
