#!/bin/bash
if [ "$dbpsql" == "" ]; then
    #load environement variable for freedom
  . /etc/freedom.conf
   wchoose -b
fi

#------------------------------
#post installation
#------------------------------
if [ "$1" = "I" ] ; then
  $wpub/wsh.php --api=freedom_import --file=$wpub/WEBDESK/webdesk.csv
fi

#------------------------------
#post update
#------------------------------
if [ "$1" = "U" ] ; then
  $wpub/wsh.php --api=freedom_import --file=$wpub/WEBDESK/webdesk.csv
fi

#------------------------------
#post uninstallation
#------------------------------
if [ "$1" = "D" ] ; then
    echo
fi
