#!/bin/bash
if [ "$dbpsql" == "" ]; then
    #load environement variable for freedom
  . /etc/freedom.conf
   wchoose -b
fi

$squirrelmail=/usr/share/squirrelmail


#------------------------------
#post installation
#------------------------------
if [ "$1" = "I" ] ; then
  $wpub/wsh.php --api=freedom_import --file=$wpub/WEBDESK/webdesk.csv


  cd $wpub/../html/phpweather
  cp $wpub/WEBDESK/phpweather-default.php /home/httpd/html/phpweather/defaults.php
  createdb -E latin1 -U anakeen phpweather
  psql -U anakeen  phpweather -c 'create table pw_metars ()'
  psql -U anakeen  phpweather -c 'create table pw_stations ()'
  psql -U anakeen  phpweather -c 'create table pw_tafs ()'
  php -q $wpub/WEBDESK/phpweather-init.php


  fth=$squirrelmail/themes/freedom_theme.php
  [ -f $fth ] && mv $fth $fth.orig
  cp $wpub/WEBDESK/squirrelmail-freedom_theme.php $fth


fi

#------------------------------
#post update
#------------------------------
if [ "$1" = "U" ] ; then

  $wpub/wsh.php --api=freedom_import --file=$wpub/WEBDESK/webdesk.csv


fi

#------------------------------
#post uninstallation
#------------------------------
if [ "$1" = "D" ] ; then

  fth=$squirrelmail/themes/freedom_theme.php
  [ -f $fth.orig ] && mv $fth.orig $fth  

  dropdb phpweather -U anakeen
  
fi
