# ============================================
# $Id: Makefile,v 1.1 2006/06/01 16:45:21 marc Exp $
# ============================================

include $(utildir)/PubRule

$(pubdir)/$(appname)/webdesk.ods : webdesk.ods
	cp webdesk.ods $(pubdir)/$(appname)

publish: $(pubdir)/$(appname)/webdesk.ods
