<?php
global $iconmap;
$iconmap = array(

		 "0cloud" => "32",
		 "0cloud_fog" => "34",
		 "1cloud_fog" => "20",
		 "1cloud_heavyrain" => "12",
		 "1cloud_modrain" => "12",
		 "1cloud_lightrain" => "9",
		 "1cloud_norain" => "30",
		 "2cloud_fog" => "20",
		 "2cloud_hail" => "37",
		 "2cloud_heavyrain" => "12",
		 "2cloud_modrain" => "12",
		 "2cloud_lightrain" => "11",
		 "2cloud_norain" => "30",
		 "2cloud_snow" => "14",
		 "3cloud_fog" => "20",
		 "3cloud_hail" => "37",
		 "3cloud_heavyrain" => "12",
		 "3cloud_modrain" => "12",
		 "3cloud_lightrain" => "11",
		 "3cloud_norain" => "28",
		 "3cloud_snow" => "16",
		 "3cloud_thunders" => "17",
		 "4cloud_fog" => "20",
		 "4cloud_hail" => "37",
		 "4cloud_heavyrain" => "12",
		 "4cloud_modrain" => "6",
		 "4cloud_lightrain" => "11",
		 "4cloud_norain" => "26",
		 "4cloud_snow" => "16",
		 "4cloud_thunders" => "35",

		 "n_0cloud" => "31",
		 "n_0cloud_fog" => "33",
		 "n_1cloud_fog" => "20",
		 "n_1cloud_heavyrain" => "12",
		 "n_1cloud_modrain" => "45",
		 "n_1cloud_lightrain" => "9",
		 "n_1cloud_norain" => "29",
		 "n_2cloud_fog" => "20",
		 "n_2cloud_hail" => "47",
		 "n_2cloud_heavyrain" => "12",
		 "n_2cloud_modrain" => "45",
		 "n_2cloud_lightrain" => "11",
		 "n_2cloud_norain" => "29",
		 "n_2cloud_snow" => "46",
		 "n_3cloud_fog" => "20",
		 "n_3cloud_hail" => "47",
		 "n_3cloud_heavyrain" => "12",
		 "n_3cloud_modrain" => "45",
		 "n_3cloud_lightrain" => "11",
		 "n_3cloud_norain" => "27",
		 "n_3cloud_snow" => "46",
		 "n_3cloud_thunders" => "47",
		 "n_4cloud_fog" => "20",
		 "n_4cloud_hail" => "47",
		 "n_4cloud_heavyrain" => "12",
		 "n_4cloud_modrain" => "45",
		 "n_4cloud_lightrain" => "11",
		 "n_4cloud_norain" => "44",
		 "n_4cloud_snow" => "46",
		 "n_4cloud_thunders" => "47"
		 );
?>