# ============================================
# $Id: Makefile,v 1.3 2007/10/22 15:16:10 marc Exp $
# ============================================
export targetdir
export utildir
include $(utildir)/PubRule
DISTFILES+=changelog changelog.in compat control copyright dirs postinst rules 
