# ============================================
# $Id: Makefile,v 1.2 2006/11/01 19:16:46 marc Exp $
# ============================================

include $(utildir)/PubRule
DISTFILES +=  webdesk.ico
$(pubdir)/$(appname)/webdesk.ico : webdesk.ico
	cp $< $(pubdir)/$(appname)/Images
publish: $(pubdir)/$(appname)/webdesk.ico 
